"""empty message

Revision ID: 1eb1e2a5089f
Revises: None
Create Date: 2016-07-12 17:53:07.008437

"""

# revision identifiers, used by Alembic.
revision = '1eb1e2a5089f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
